# C2 Server Configuration

server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  workers: 4

database:
  # SQLite for development
  url: "sqlite:///./c2_teamserver.db"
  
  # PostgreSQL for production
  # url: "postgresql://c2user:c2pass@localhost/c2db"
  
  pool_size: 20
  max_overflow: 40

redis:
  url: "redis://localhost:6379"
  
security:
  secret_key: "change-this-in-production"
  token_expire_minutes: 720
  default_admin_password: "changeme123!"
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

storage:
  upload_dir: "./uploads"
  download_dir: "./downloads"
  payload_dir: "./payloads"
  max_upload_size: 104857600  # 100MB

logging:
  level: "INFO"
  file: "./logs/c2_server.log"
  max_size: 104857600  # 100MB
  backup_count: 10

listeners:
  defaults:
    check_interval: 30
    timeout: 300

agents:
  defaults:
    sleep_interval: 60
    jitter: 10
    timeout: 300

ssl:
  cert_dir: "./certs"
  auto_generate: true
